[package]
name = "hello-rust2"
version = "0.1.0"
authors = ["kchapelier <kevin.chapelier@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"